## <center>IMDB DataSet Evaluation:

In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('DataSet/imdb_1000.csv')

In [7]:
movies.head(-1)

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."

In [12]:
genres = movies.groupby('genre')
genres.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
638,7.7,The City of Lost Children,R,Fantasy,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ..."
687,7.7,Spellbound,UNRATED,Film-Noir,111,"[u'Ingrid Bergman', u'Gregory Peck', u'Michael..."
728,7.6,La piel que habito,R,Thriller,120,"[u'Antonio Banderas', u'Elena Anaya', u'Jan Co..."
848,7.5,The Man Who Knew Too Much,PG,Thriller,120,"[u'James Stewart', u'Doris Day', u'Brenda de B..."
902,7.5,Frenzy,R,Thriller,116,"[u'Jon Finch', u'Barry Foster', u'Alec McCowen']"

In [21]:
genres.get_group('Thriller')
#movies[movies['genre']== 'Thriller']

,star_rating,title,content_rating,genre,duration,actors_list
350,8.0,Shadow of a Doubt,APPROVED,Thriller,108,"[u'Teresa Wright', u'Joseph Cotten', u'Macdona..."
496,7.8,Misery,R,Thriller,107,"[u'James Caan', u'Kathy Bates', u'Richard Farn..."
728,7.6,La piel que habito,R,Thriller,120,"[u'Antonio Banderas', u'Elena Anaya', u'Jan Co..."
848,7.5,The Man Who Knew Too Much,PG,Thriller,120,"[u'James Stewart', u'Doris Day', u'Brenda de B..."
902,7.5,Frenzy,R,Thriller,116,"[u'Jon Finch', u'Barry Foster', u'Alec McCowen']"

In [22]:
genres.groups

{'Action': [3, 11, 12, 19, 20, 36, 37, 43, 44, 45, 75, 80, 82, 96, 100, 113, 118, 123, 129, 135, 138, 152, 163, 173, 177, 194, 196, 198, 235, 239, 240, 248, 261, 268, 276, 281, 296, 301, 312, 327, 349, 354, 366, 380, 385, 388, 391, 401, 403, 409, 411, 420, 433, 434, 437, 440, 452, 455, 469, 470, 488, 491, 502, 509, 515, 517, 529, 531, 532, 533, 534, 539, 552, 563, 567, 568, 570, 573, 581, 586, 591, 598, 610, 613, 619, 623, 633, 649, 653, 661, 671, 675, 683, 684, 685, 686, 691, 699, 701, 707, ...], 'Adventure': [7, 10, 14, 15, 54, 68, 71, 85, 101, 114, 120, 128, 133, 137, 140, 142, 164, 179, 204, 206, 214, 222, 224, 245, 271, 299, 309, 310, 328, 333, 336, 339, 359, 362, 368, 376, 393, 419, 424, 429, 445, 454, 479, 510, 520, 522, 537, 551, 555, 564, 576, 605, 629, 642, 658, 662, 698, 727, 754, 758, 794, 814, 852, 891, 898, 900, 909, 911, 932, 935, 936, 937, 943, 953, 975], 'Animation': [30, 55, 61, 64, 69, 81, 117, 126, 131, 147, 160, 167, 192, 193, 241, 256, 277, 294, 303, 305, 308, 332, 343, 357, 378, 381, 386, 395, 414, 417, 443, 453, 461, 471, 487, 489, 494, 498, 501, 512, 518, 541, 607, 617, 625, 656, 657, 664, 669, 674, 713, 743, 759, 766, 789, 820, 835, 844, 853, 882, 938, 966], 'Biography': [8, 18, 31, 42, 99, 124, 125, 143, 148, 156, 170, 187, 197, 201, 209, 220, 260, 273, 274, 286, 302, 313, 340, 341, 346, 348, 400, 410, 418, 423, 442, 446, 447, 450, 460, 500, 514, 536, 547, 550, 554, 560, 561, 569, 574, 579, 585, 601, 626, 627, 630, 660, 682, 690, 700, 725, 756, 763, 776, 782, 788, 804, 807, 811, 817, 818, 824, 825, 829, 840, 876, 888, 892, 903, 930, 961, 964], 'Comedy': [25, 29, 35, 48, 52, 60, 66, 70, 88, 93, 94, 97, 103, 106, 109, 111, 144, 151, 153, 155, 165, 183, 189, 190, 208, 231, 246, 252, 254, 255, 265, 266, 275, 280, 282, 285, 287, 293, 298, 304, 306, 314, 315, 319, 352, 356, 358, 367, 370, 382, 394, 399, 435, 451, 458, 459, 462, 464, 465, 472, 475, 480, 483, 486, 516, 519, 524, 527, 535, 542, 545, 546, 553, 557, 565, 578, 580, 582, 584, 588, 590, 593, 595, 597, 599, 602, 608, 611, 612, 614, 615, 622, 631, 639, 640, 641, 646, 650, 663, 667, ...], 'Crime': [0, 1, 2, 4, 21, 23, 28, 34, 40, 49, 63, 65, 78, 79, 86, 90, 92, 98, 112, 115, 122, 154, 169, 171, 175, 176, 178, 182, 199, 200, 212, 216, 217, 225, 229, 233, 234, 253, 257, 258, 272, 278, 290, 297, 300, 324, 329, 365, 369, 383, 384, 407, 412, 413, 425, 426, 436, 438, 441, 466, 474, 478, 482, 492, 493, 495, 506, 549, 556, 566, 571, 577, 587, 596, 616, 621, 624, 636, 648, 651, 652, 666, 670, 677, 681, 694, 697, 711, 724, 730, 732, 746, 747, 757, 761, 784, 786, 797, 799, 802, ...], 'Drama': [5, 9, 13, 16, 17, 22, 24, 27, 32, 33, 41, 47, 50, 51, 53, 56, 58, 67, 72, 73, 74, 77, 83, 84, 87, 89, 91, 95, 102, 104, 108, 116, 121, 127, 130, 132, 134, 136, 139, 141, 146, 150, 157, 158, 159, 162, 166, 168, 172, 174, 180, 181, 184, 185, 188, 191, 195, 202, 203, 205, 207, 211, 213, 215, 218, 219, 221, 223, 226, 227, 228, 230, 232, 237, 238, 242, 243, 247, 250, 251, 259, 262, 267, 269, 270, 279, 283, 284, 288, 289, 291, 295, 307, 311, 316, 318, 320, 323, 325, 326, ...], 'Family': [468, 497], 'Fantasy': [638], 'Film-Noir': [105, 210, 687], 'History': [338], 'Horror': [39, 57, 62, 161, 186, 317, 322, 330, 351, 353, 405, 513, 572, 655, 688, 703, 708, 736, 769, 779, 796, 847, 860, 864, 869, 881, 905, 913, 977], 'Mystery': [38, 46, 76, 110, 149, 244, 249, 264, 292, 467, 583, 742, 863, 866, 894, 965], 'Sci-Fi': [145, 321, 408, 484, 637], 'Thriller': [350, 496, 728, 848, 902], 'Western': [6, 26, 59, 107, 119, 236, 263, 421, 704]}

In [23]:
genres.describe()

          star_rating                                                    \
                count      mean       std  min    25%   50%    75%  max
genre
Action          136.0  7.884559  0.333084  7.4  7.600  7.80  8.100  9.0
Adventure        75.0  7.933333  0.361802  7.4  7.650  7.90  8.100  8.9
Animation        62.0  7.914516  0.292444  7.4  7.700  7.90  8.100  8.6
Biography        77.0  7.862338  0.310364  7.4  7.600  7.80  8.100  8.9
Comedy          156.0  7.822436  0.304922  7.4  7.600  7.80  8.000  8.6
Crime           124.0  7.916935  0.392143  7.4  7.600  7.80  8.100  9.3
Drama           278.0  7.902518  0.328041  7.4  7.600  7.90  8.100  8.9
Family            2.0  7.850000  0.070711  7.8  7.825  7.85  7.875  7.9
Fantasy           1.0  7.700000       NaN  7.7  7.700  7.70  7.700  7.7
Film-Noir         3.0  8.033333  0.305505  7.7  7.900  8.10  8.200  8.3
History           1.0  8.000000       NaN  8.0  8.000  8.00  8.000  8.0
Horror           29.0  7.806897  0.337989  7.4  7.500  7.70  8.000  8.6
Mystery          16.0  7.975000  0.387298  7.4  7.575  8.10  8.225  8.6
Sci-Fi            5.0  7.920000  0.192354  7.7  7.800  7.90  8.000  8.2
Thriller          5.0  7.680000  0.216795  7.5  7.500  7.60  7.800  8.0
Western           9.0  8.255556  0.387657  7.6  8.100  8.30  8.500  8.9

          duration
             count        mean        std    min     25%    50%     75%    max
genre
Action       136.0  126.485294  21.982480   80.0  111.00  125.0  137.00  205.0
Adventure     75.0  134.840000  33.383942   89.0  109.00  127.0  151.50  224.0
Animation     62.0   96.596774  13.975927   75.0   87.00   94.5  102.00  134.0
Biography     77.0  131.844156  24.283991   85.0  116.00  127.0  146.00  202.0
Comedy       156.0  107.602564  20.101574   68.0   94.00  104.0  117.00  187.0
Crime        124.0  122.298387  25.054406   67.0  104.75  118.0  134.25  229.0
Drama        278.0  126.539568  25.637086   64.0  108.00  123.0  138.00  242.0
Family         2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy        1.0  112.000000        NaN  112.0  112.00  112.0  112.00  112.0
Film-Noir      3.0   97.333333  12.096832   88.0   90.50   93.0  102.00  111.0
History        1.0   66.000000        NaN   66.0   66.00   66.0   66.00   66.0
Horror        29.0  102.517241  18.908843   70.0   85.00  104.0  116.00  146.0
Mystery       16.0  115.625000  22.585762   69.0  103.75  115.0  129.25  160.0
Sci-Fi         5.0  109.000000  17.478558   91.0   92.00  113.0  117.00  132.0
Thriller       5.0  114.200000   6.340347  107.0  108.00  116.0  120.00  120.0
Western        9.0  136.666667  28.748913   85.0  131.00  135.0  161.00  175.0

In [24]:
genres.nunique()

           star_rating  title  content_rating  duration  actors_list
genre
Action              16    136               9        65          134
Adventure           15     74               8        59           68
Animation           13     62               7        31           61
Biography           15     77               7        52           77
Comedy              13    156              11        62          156
Crime               18    123               9        66          124
Drama               16    278              11        94          278
Family               2      2               2         2            2
Fantasy              1      1               1         1            1
Film-Noir            3      3               3         3            3
History              1      1               1         1            1
Horror              10     28               8        26           29
Mystery             11     16               7        15           16
Sci-Fi               5      5               3         5            5
Thriller             4      5               3         4            5
Western              7      9               5         9            9